<?php

/**
 * Implements hook_menu().
 */
function cdt_issues_menu() {
  $items = array();
  $items['migrate/issues'] = array(
    'title' => 'Migrate CDT Issues',
    'description' => 'Migrate Issue content to Issues taxonomy.',
    'page callback' => 'cdt_issues_issues',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['migrate/taxonomy'] = array(
    'title' => 'Migrate CDT Issues',
    'description' => 'Migrate node references to taxonomy references.',
    'page callback' => 'cdt_issues_taxonomy',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

